# No hierarchy
NO_HIERARCHY:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [1,3,3]
  STRIDE: [1,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [1,3,3]
  STRIDE: [1,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [1,3,3]
  STRIDE: [1,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,3,3]
  STRIDE: [2,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_6:
  IN_CHANNEL: 32
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,1,1]
  STRIDE: [2,1,1]
  PADDING: [0,0,0]
  BIAS: False
 SUBBLOCK_7:
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True

# One hierarchy
ONE_HIERARCHY:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [3,3,3] # <--
  STRIDE: [3,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [1,3,3]
  STRIDE: [1,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [1,3,3]
  STRIDE: [1,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,3,3]
  STRIDE: [2,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_6:
  IN_CHANNEL: 32
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,1,1]
  STRIDE: [2,1,1]
  PADDING: [0,0,0]
  BIAS: False
 SUBBLOCK_7:
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True

# Two hierarchy
TWO_HIERARCHY:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [3,3,3] # <--
  STRIDE: [3,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [5,3,3]  # <--
  STRIDE: [5,1,1]  # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [1,3,3]
  STRIDE: [1,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,3,3]
  STRIDE: [2,1,1]
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_6:
  IN_CHANNEL: 32
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,1,1]
  STRIDE: [2,1,1]
  PADDING: [0,0,0]
  BIAS: False
 SUBBLOCK_7:
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True

# CLIP_SIZE 8
CLIP_SIZE_8:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [3,3,3] # <--
  STRIDE: [3,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [5,3,3]  # <--
  STRIDE: [5,1,1]  # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [5,3,3] # <--
  STRIDE: [5,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [1,3,3] # <--
  STRIDE: [1,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_7: # <--
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True

# CLIP_SIZE 16
CLIP_SIZE_16:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [3,3,3] # <--
  STRIDE: [3,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [5,3,3]  # <--
  STRIDE: [5,1,1]  # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [5,3,3] # <--
  STRIDE: [5,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,3,3] # <-- from clip slize 8
  STRIDE: [2,1,1] # <-- from clip slize 8
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_7:
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True

# CLIP_SIZE 32
CLIP_SIZE_32:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [3,3,3] # <--
  STRIDE: [3,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [5,3,3]  # <--
  STRIDE: [5,1,1]  # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [5,3,3] # <--
  STRIDE: [5,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,3,3] # <-- from clip slize 8
  STRIDE: [2,1,1] # <-- from clip slize 8
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_6:
  IN_CHANNEL: 32
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,1,1]
  STRIDE: [2,1,1]
  PADDING: [0,0,0]
  BIAS: False
 SUBBLOCK_7:
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True

# CLIP_SIZE 48
CLIP_SIZE_48:
 SUBBLOCK_1:
  IN_CHANNEL: 1024
  OUT_CHANNEL: 832
  KERNEL_SIZE: [1, 3, 3]
  STRIDE: [1, 1, 1]
  PADDING: [0, 1, 1]
  BIAS: False
 SUBBLOCK_2:
  IN_CHANNEL: 832
  OUT_CHANNEL: 480
  KERNEL_SIZE: [3,3,3] # <--
  STRIDE: [3,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_3:
  IN_CHANNEL: 480
  OUT_CHANNEL: 192
  KERNEL_SIZE: [5,3,3]  # <--
  STRIDE: [5,1,1]  # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_4:
  IN_CHANNEL: 192
  OUT_CHANNEL: 64
  KERNEL_SIZE: [5,3,3] # <--
  STRIDE: [5,1,1] # <--
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_5:
  IN_CHANNEL: 64
  OUT_CHANNEL: 32
  KERNEL_SIZE: [2,3,3] # <-- from clip slize 8
  STRIDE: [2,1,1] # <-- from clip slize 8
  PADDING: [0,1,1]
  BIAS: False
 SUBBLOCK_6:
  IN_CHANNEL: 32
  OUT_CHANNEL: 32
  KERNEL_SIZE: [3,1,1] # <-- from clip slize 32
  STRIDE: [3,1,1] # <-- from clip slize 32
  PADDING: [0,0,0]
  BIAS: True
 SUBBLOCK_7:
  IN_CHANNEL: 32
  OUT_CHANNEL: 1
  KERNEL_SIZE: [1,1,1]
  STRIDE: [1,1,1]
  PADDING: [0,0,0]
  BIAS: True